### PR TITLE
IronScheme support

### PR DESCRIPTION
**Pull request by leppie**
Hi

Tried to fill in most of the few gaps. 

`test-all.ss` passes on Windows and Linux (.NET Core). (Should be fine on MacOS too)

This is a work in progress.

FYI: IronScheme is psyntax-based and probably matches Ikarus/Vicare the best. 

Also, this runs very slow on Linux. 🐌 (win clr v2 is ~ 3.4 faster)

Useless info: nanopass tests exposed 2 very old bugs in the IronScheme compiler 💃

### CODE REVIEW

**Comment by leppie** [comment]
Ping @akeep

**Comment by akeep** [comment]
Apologies for the extremely slow response.  I'm quite excited about this, but I don't have a windows machine easily at hand, and since December I've moved across the country, started a new job, and I'm working on preparing a couple of talks for ELS2020, so things have been a bit crazy.

I'm hoping to get a Windows VM setup so that I can give this a test on IronScheme, but it may still be a month or two before I get a few free evenings or a free weekend to look at it.

**Comment by weinholt** [comment]
@akeep IronScheme also runs on Linux. The [schemers/ironscheme](https://hub.docker.com/repository/docker/schemers/ironscheme) Docker image is an easy way to get going. It even has a `scheme-script` wrapper.

FWIW, Loko Scheme is also psyntax-based, should be easy to get nanopass running on that.

**Comment by akeep** [comment]
Looks good!  I was able to test it out on macOS as well.  It is a bit slow there too, but not too bad :)  Glad to hear it is faster on windows!

**Pull request merged**
